export const SUBJECTS = [
  'Java',
  'Python',
  'JavaScript',
  'Banco de Dados',
  'Redes',
  'Sistemas Operacionais',
  'Logica de Programacao',
  'Portugues',
  'Matematica',
  'Direito',
  'Direito Constitucional',
  'Direito Civil',
  'Administracao',
  'Contabilidade',
  'ENEM',
  'Medicina',
  'Cardiologia',
  'Enfermagem',
  'Farmacologia',
  'Anatomia',
  'Fisica',
  'Quimica',
  'Biologia',
  'Historia',
  'Geografia',
  'Informatica',
] as const;
